### ISSUE TITLE
Peer to peer code review issues

### ISSUE THREAD

**Issue by Bennyjoez** [dev89s/portfolio#4]
<img src="https://media1.giphy.com/media/229OX0vSVNys10AZnS/giphy.gif"/>

<strong>PEER TO PEER REVIEW ISSUES</strong> ♻️ 
I think the following areas need your attention: 
> Kindly remove the unused div element. 🔴 
https://github.com/dev89s/portfolio/blob/b0c217b5e24e8d7611be15908b24fa16700fe800/index.html#L60

> Kindly remove the href attribute from the button as it is not a valid button attribute. 😄  
https://github.com/dev89s/portfolio/blob/b0c217b5e24e8d7611be15908b24fa16700fe800/index.html#L85

**Comment by dev89s** [comment]
The problems you mentioned are fixed.
